version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-229-106.compute-1.amazonaws.com
            database: d52pnu0vpdoitu
            schema: public
            user: aboooriflopqmt
            password: 8f385b050ee50371a06a51c213b6471339e88e0fa71a3ec4a429f71c2da6c416
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true