version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-22-228-141.compute-1.amazonaws.com
            database: d4sjj78tr1k87p
            user: tvzjeqogphpigj
            password: aaed8a98a20bd249ff612d0067bc6373d6062d6e05caf95cafe75ac87179f1ee
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true